name: Publish Agent Package

on:
  push:
    tags:
      - "agent-v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (without v prefix)"
        required: true
        default: "0.1.0"
  workflow_call:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string

# Adding permissions at workflow level
permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/pypi-reusable-publish.yml
    with:
      package_name: "agent"
      package_dir: "libs/python/agent"
      version: "" # Version will be read from pyproject.toml
      is_lume_package: false
      base_package_name: "cua-agent"
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
